# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 58052b770ec844d052d7cf407b748cc61cb60ec469160dfac2cb93de61f53032ba051f75d646f0c17ebe12513267ea1cb1a5052170d5f4a94ab57d5d26ca1e05

test:
  secret_key_base: ee7be7ea9d454953543f211ee5ac6ca81694f3e55b81a963631c72bafd81b8504bdb81f5be2be640cdb809f6ae125d196d0d995de570b0a61c0e574951391cd2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
